version: "3.5"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  
  api:
    build: ./
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db